# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'databaseViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(466, 518)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 210, 411, 241))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.BW_orderhis_B_refresh = QtWidgets.QPushButton(self.centralwidget)
        self.BW_orderhis_B_refresh.setGeometry(QtCore.QRect(290, 460, 151, 31))
        self.BW_orderhis_B_refresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/alexa/Downloads/Icons/icons/arrow-retweet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BW_orderhis_B_refresh.setIcon(icon)
        self.BW_orderhis_B_refresh.setIconSize(QtCore.QSize(32, 32))
        self.BW_orderhis_B_refresh.setObjectName("BW_orderhis_B_refresh")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 460, 141, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.selectFile = QtWidgets.QPushButton(self.centralwidget)
        self.selectFile.setGeometry(QtCore.QRect(30, 20, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.selectFile.setFont(font)
        self.selectFile.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectFile.setMouseTracking(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Assets/opendb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectFile.setIcon(icon1)
        self.selectFile.setIconSize(QtCore.QSize(30, 30))
        self.selectFile.setCheckable(False)
        self.selectFile.setObjectName("selectFile")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 100, 221, 22))
        self.comboBox.setObjectName("comboBox")
        self.gobutton = QtWidgets.QPushButton(self.centralwidget)
        self.gobutton.setGeometry(QtCore.QRect(30, 130, 401, 23))
        self.gobutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.gobutton.setObjectName("gobutton")
        self.databaseLabel = QtWidgets.QLabel(self.centralwidget)
        self.databaseLabel.setGeometry(QtCore.QRect(260, 30, 161, 16))
        self.databaseLabel.setObjectName("databaseLabel")
        self.tableLabel = QtWidgets.QLabel(self.centralwidget)
        self.tableLabel.setGeometry(QtCore.QRect(260, 100, 171, 16))
        self.tableLabel.setObjectName("tableLabel")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Database Viewer"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "3"))
        self.BW_orderhis_B_refresh.setText(_translate("mainWindow", "Search Database"))
        self.lineEdit.setText(_translate("mainWindow", "Search in Database"))
        self.selectFile.setText(_translate("mainWindow", "Open Database"))
        self.gobutton.setText(_translate("mainWindow", "Go!"))
        self.databaseLabel.setText(_translate("mainWindow", "No file selected."))
        self.tableLabel.setText(_translate("mainWindow", "No table selected."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
